/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Appliance = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'brandIds' : IDL.Vec(IDL.Nat),
});
export const Brand = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'brandId' : IDL.Nat,
  'price' : IDL.Float64,
  'applianceId' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllAppliances' : IDL.Func([], [IDL.Vec(Appliance)], ['query']),
  'getAllBrands' : IDL.Func([], [IDL.Vec(Brand)], ['query']),
  'getBrandsForAppliance' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(IDL.Vec(Brand))],
      ['query'],
    ),
  'getProductsByIds' : IDL.Func(
      [IDL.Vec(IDL.Nat)],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'searchProducts' : IDL.Func(
      [IDL.Vec(IDL.Nat), IDL.Vec(IDL.Nat), IDL.Opt(IDL.Float64)],
      [IDL.Vec(Product), IDL.Nat],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Appliance = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'brandIds' : IDL.Vec(IDL.Nat),
  });
  const Brand = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'brandId' : IDL.Nat,
    'price' : IDL.Float64,
    'applianceId' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllAppliances' : IDL.Func([], [IDL.Vec(Appliance)], ['query']),
    'getAllBrands' : IDL.Func([], [IDL.Vec(Brand)], ['query']),
    'getBrandsForAppliance' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(IDL.Vec(Brand))],
        ['query'],
      ),
    'getProductsByIds' : IDL.Func(
        [IDL.Vec(IDL.Nat)],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'searchProducts' : IDL.Func(
        [IDL.Vec(IDL.Nat), IDL.Vec(IDL.Nat), IDL.Opt(IDL.Float64)],
        [IDL.Vec(Product), IDL.Nat],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };