/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appliance {
  'id' : bigint,
  'name' : string,
  'brandIds' : Array<bigint>,
}
export interface Brand { 'id' : bigint, 'name' : string }
export interface Product {
  'id' : bigint,
  'name' : string,
  'brandId' : bigint,
  'price' : number,
  'applianceId' : bigint,
}
export interface _SERVICE {
  /**
   * / Retrieve all appliances static data
   */
  'getAllAppliances' : ActorMethod<[], Array<Appliance>>,
  /**
   * / Retrieve all brands static data
   */
  'getAllBrands' : ActorMethod<[], Array<Brand>>,
  /**
   * / Retrieve all brands for a specific appliance by brandIds
   */
  'getBrandsForAppliance' : ActorMethod<[bigint], [] | [Array<Brand>]>,
  /**
   * / Bulk fetch specific products by IDs (if not implemented client-side)
   */
  'getProductsByIds' : ActorMethod<[Array<bigint>], Array<Product>>,
  /**
   * / Search for products not explicitly needed due to static data
   */
  'searchProducts' : ActorMethod<
    [Array<bigint>, Array<bigint>, [] | [number]],
    [Array<Product>, bigint]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];