/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appliance {
  'id' : bigint,
  'name' : string,
  'brandIds' : Array<bigint>,
}
export interface Brand { 'id' : bigint, 'name' : string }
export interface Product {
  'id' : bigint,
  'name' : string,
  'brandId' : bigint,
  'price' : number,
  'applianceId' : bigint,
}
export interface ServiceRequest {
  'id' : bigint,
  'status' : string,
  'city' : string,
  'postalCode' : string,
  'name' : string,
  'email' : string,
  'creationTime' : bigint,
  'message' : string,
  'preferredTime' : string,
  'applianceType' : string,
  'brand' : string,
  'phone' : string,
  'applianceAge' : string,
}
export interface ServiceRequestInput {
  'city' : string,
  'postalCode' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'preferredTime' : string,
  'applianceType' : string,
  'brand' : string,
  'phone' : string,
  'applianceAge' : string,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / COMPONENT: Service Request - Create Request
   */
  'createServiceRequest' : ActorMethod<
    [ServiceRequestInput],
    { 'requestId' : bigint, 'confirmationMessage' : string }
  >,
  /**
   * / COMPONENT: Service Request - Admin Bulk Delete
   */
  'deleteAllServiceRequests' : ActorMethod<
    [],
    { 'deletedRequestIds' : Array<bigint>, 'message' : string }
  >,
  /**
   * / COMPONENT: Service Request - Admin Delete
   */
  'deleteServiceRequest' : ActorMethod<
    [bigint],
    { 'message' : string, 'deletedRequestId' : bigint }
  >,
  'getAllAppliances' : ActorMethod<[], Array<Appliance>>,
  'getAllBrands' : ActorMethod<[], Array<Brand>>,
  /**
   * / COMPONENT: Service Request - Admin Get All
   */
  'getAllServiceRequests' : ActorMethod<[], Array<ServiceRequest>>,
  'getBrandsForAppliance' : ActorMethod<[bigint], [] | [Array<Brand>]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProductsByIds' : ActorMethod<[Array<bigint>], Array<Product>>,
  /**
   * / COMPONENT: Service Request - Admin Get Single
   */
  'getServiceRequest' : ActorMethod<[bigint], ServiceRequest>,
  /**
   * / COMPONENT: Service Request Count - Admin
   */
  'getServiceRequestCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProducts' : ActorMethod<
    [Array<bigint>, Array<bigint>, [] | [number]],
    [Array<Product>, bigint]
  >,
  /**
   * / COMPONENT: Service Request - Admin Update
   */
  'updateServiceRequest' : ActorMethod<
    [bigint, ServiceRequestInput],
    ServiceRequest
  >,
  /**
   * / COMPONENT: Service Request - Admin Update Status
   */
  'updateServiceRequestStatus' : ActorMethod<
    [bigint, string],
    { 'id' : bigint, 'newStatus' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];